name: GeoNode Layer CSV scraper

on:
  workflow_dispatch:
  schedule:
    - cron:  '10,30,50 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl "https://master.demo.geonode.org/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typename=geonode%3Aswamp&outputFormat=csv&srs=EPSG%3A2964" > swamp.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
