name: GeoNode Layer scraper

on:
  workflow_dispatch:
  schedule:
    - cron:  '8,28,48 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g geojson-rewind      
    - run: |-
        curl "https://master.demo.geonode.org/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typename=geonode%3Aswamp&outputFormat=json&srs=EPSG%3A4326&srsName=EPSG%3A4326" | jq 'del(.requested_time,.crs,.timeStamp)' > swamp_tmp.geojson        
    - run: geojson-rewind swamp_tmp.geojson > swamp.geojson 
    - run: rm swamp_tmp.geojson 
    - run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push