name: GeoNode Profile scraper

on:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl "https://master.demo.geonode.org/api/profiles/?abstract__icontains=Toni&f_method=or&limit=5&offset=0&purpose__icontains=Toni&username__icontains=Toni" | jq 'del(.requested_time)' > profiles.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
